// GENERATED by scripts/build-themes.ts — do not edit by hand.
// Run `bun run build:themes` after changing anything under themes/.
export const THEME_INFO = [
  {
    "slug": "academic",
    "name": "Academic",
    "description": "LaTeX-paper look: warm-white page, Palatino serif, justified text, booktabs tables, centered headings. For reports that should read like a published paper."
  },
  {
    "slug": "cyberpunk",
    "name": "Night City",
    "description": "Cyberpunk 2077: acid yellow on black, clipped corners, cyan links that flicker red. Flat and hard-edged — wake up, samurai."
  },
  {
    "slug": "matrix",
    "name": "Matrix",
    "description": "Phosphor-green code-rain terminal: #00ff41 on black, glow text, scanlines, monospace everything. Follow the white rabbit."
  },
  {
    "slug": "plivo",
    "name": "Plivo",
    "description": "Developer-precision, monochrome-first: near-neutral surfaces, one blue accent, Sora display type, JetBrains Mono metadata, hairline elevation. First-class light and dark."
  },
  {
    "slug": "synthwave",
    "name": "Synthwave '84",
    "description": "Outrun neon: deep-purple night, hot-pink glow headings, cyan links, a sunset-gradient rule. The only theme that glows."
  },
  {
    "slug": "win98",
    "name": "Windows 98",
    "description": "Silver chrome, navy title-bar headings, beveled buttons, sunken white fields. It is now safe to turn off your computer."
  }
] as const

export type ThemeSlug = (typeof THEME_INFO)[number]['slug']

const SLUGS = new Set<string>(THEME_INFO.map((t) => t.slug))

/** True when `v` names a shipped theme. The single validation authority for sites.theme. */
export function isTheme(v: unknown): v is ThemeSlug {
  return typeof v === 'string' && SLUGS.has(v)
}
