// A hand-curated emoji set, deliberately NOT a library. Every emoji package either ships the full
// ~1900-entry unicode table (and its keyword index) into the bundle or fetches sheets from a CDN at
// runtime; a comment composer needs neither. ~200 glyphs cover what people actually react and reply
// with, and the whole file costs less than the loader a library would need.
//
// Keywords carry the words the NAME doesn't: `lol` for 😂, `+1` for 👍, `ship` for 🚀. That is the
// only reason search finds anything useful, so an entry with no keywords is a bug (asserted in the
// tests).

export interface Emoji {
  emoji: string
  name: string
  keywords: string[]
}

export interface EmojiCategory {
  name: string
  emojis: Emoji[]
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: 'Smileys',
    emojis: [
      { emoji: '😀', name: 'grinning', keywords: ['smile', 'happy', 'grin'] },
      { emoji: '😃', name: 'grinning big eyes', keywords: ['smile', 'happy', 'joy'] },
      { emoji: '😄', name: 'grinning smiling eyes', keywords: ['smile', 'happy', 'laugh'] },
      { emoji: '😁', name: 'beaming', keywords: ['grin', 'smile', 'teeth'] },
      { emoji: '😆', name: 'squinting laugh', keywords: ['laugh', 'haha', 'lol'] },
      { emoji: '😅', name: 'grinning sweat', keywords: ['laugh', 'relief', 'phew'] },
      { emoji: '🤣', name: 'rolling on the floor laughing', keywords: ['rofl', 'lol', 'laugh'] },
      { emoji: '😂', name: 'tears of joy', keywords: ['lol', 'laugh', 'funny', 'cry'] },
      { emoji: '🙂', name: 'slightly smiling', keywords: ['smile', 'happy', 'ok'] },
      { emoji: '🙃', name: 'upside-down', keywords: ['silly', 'sarcasm', 'irony'] },
      { emoji: '😉', name: 'winking', keywords: ['wink', 'flirt', 'joke'] },
      { emoji: '😊', name: 'smiling eyes', keywords: ['blush', 'happy', 'warm'] },
      { emoji: '😇', name: 'halo', keywords: ['angel', 'innocent', 'good'] },
      { emoji: '🥰', name: 'smiling with hearts', keywords: ['love', 'adore', 'crush'] },
      { emoji: '😍', name: 'heart eyes', keywords: ['love', 'crush', 'adore'] },
      { emoji: '😘', name: 'blowing a kiss', keywords: ['kiss', 'love'] },
      { emoji: '😋', name: 'savoring food', keywords: ['yum', 'tasty', 'delicious'] },
      { emoji: '😜', name: 'winking tongue', keywords: ['silly', 'joke', 'cheeky'] },
      { emoji: '🤪', name: 'zany', keywords: ['crazy', 'wild', 'silly'] },
      { emoji: '🤨', name: 'raised eyebrow', keywords: ['suspicious', 'skeptical', 'doubt'] },
      { emoji: '🧐', name: 'monocle', keywords: ['inspect', 'scrutiny', 'examine'] },
      { emoji: '🤓', name: 'nerd', keywords: ['geek', 'smart', 'glasses'] },
      { emoji: '😎', name: 'sunglasses', keywords: ['cool', 'chill', 'shades'] },
      { emoji: '🥳', name: 'partying', keywords: ['celebrate', 'party', 'birthday'] },
      { emoji: '😏', name: 'smirking', keywords: ['smug', 'smirk', 'sly'] },
      { emoji: '😒', name: 'unamused', keywords: ['meh', 'unimpressed', 'annoyed'] },
      { emoji: '😞', name: 'disappointed', keywords: ['sad', 'let down'] },
      { emoji: '😔', name: 'pensive', keywords: ['sad', 'thoughtful', 'down'] },
      { emoji: '😴', name: 'sleeping', keywords: ['sleep', 'zzz', 'tired'] },
      { emoji: '🤔', name: 'thinking', keywords: ['think', 'hmm', 'consider'] },
      { emoji: '🤫', name: 'shushing', keywords: ['quiet', 'shh', 'secret'] },
      { emoji: '🤯', name: 'exploding head', keywords: ['mind blown', 'shock', 'wow'] },
      { emoji: '😱', name: 'screaming in fear', keywords: ['scream', 'shock', 'horror'] },
      { emoji: '😳', name: 'flushed', keywords: ['embarrassed', 'surprise', 'blush'] },
      { emoji: '🥺', name: 'pleading', keywords: ['please', 'beg', 'puppy eyes'] },
      { emoji: '😢', name: 'crying', keywords: ['sad', 'tear', 'cry'] },
      { emoji: '😭', name: 'loudly crying', keywords: ['sob', 'cry', 'sad'] },
      { emoji: '😤', name: 'steam from nose', keywords: ['frustrated', 'triumph', 'determined'] },
      { emoji: '😡', name: 'pouting', keywords: ['angry', 'mad', 'rage'] },
      { emoji: '🤬', name: 'cursing', keywords: ['swear', 'angry', 'symbols'] },
      { emoji: '😬', name: 'grimacing', keywords: ['awkward', 'cringe', 'eek'] },
      { emoji: '🥲', name: 'smiling with tear', keywords: ['grateful', 'bittersweet', 'proud'] },
      { emoji: '🤗', name: 'hugging', keywords: ['hug', 'embrace', 'thanks'] },
      { emoji: '😐', name: 'neutral', keywords: ['meh', 'blank', 'deadpan'] },
      { emoji: '🙄', name: 'rolling eyes', keywords: ['eyeroll', 'annoyed', 'whatever'] },
      { emoji: '😷', name: 'medical mask', keywords: ['sick', 'mask', 'ill'] },
      { emoji: '🤒', name: 'thermometer face', keywords: ['sick', 'fever', 'ill'] },
      { emoji: '🥱', name: 'yawning', keywords: ['tired', 'bored', 'sleepy'] },
      { emoji: '🤢', name: 'nauseated', keywords: ['sick', 'gross', 'disgust'] },
      { emoji: '🫡', name: 'saluting', keywords: ['salute', 'respect', 'yes'] },
      { emoji: '💀', name: 'skull', keywords: ['dead', 'dying', 'lol'] },
      { emoji: '👻', name: 'ghost', keywords: ['spooky', 'halloween', 'boo'] },
      { emoji: '🤖', name: 'robot', keywords: ['bot', 'ai', 'automation'] },
      { emoji: '👽', name: 'alien', keywords: ['ufo', 'space', 'extraterrestrial'] },
      { emoji: '🤡', name: 'clown', keywords: ['joke', 'silly', 'fool'] },
      { emoji: '💩', name: 'pile of poo', keywords: ['poop', 'crap', 'bad'] },
    ],
  },
  {
    name: 'Gestures',
    emojis: [
      { emoji: '👍', name: 'thumbs up', keywords: ['+1', 'yes', 'approve', 'like'] },
      { emoji: '👎', name: 'thumbs down', keywords: ['-1', 'no', 'disapprove', 'dislike'] },
      { emoji: '👏', name: 'clapping hands', keywords: ['applause', 'bravo', 'clap'] },
      { emoji: '🙌', name: 'raising hands', keywords: ['celebrate', 'praise', 'yay'] },
      { emoji: '🙏', name: 'folded hands', keywords: ['please', 'thanks', 'pray'] },
      { emoji: '🤝', name: 'handshake', keywords: ['deal', 'agree', 'partnership'] },
      { emoji: '👌', name: 'ok hand', keywords: ['ok', 'perfect', 'fine'] },
      { emoji: '🤌', name: 'pinched fingers', keywords: ['italian', 'chef kiss', 'precise'] },
      { emoji: '✌️', name: 'victory hand', keywords: ['peace', 'two'] },
      { emoji: '🤞', name: 'crossed fingers', keywords: ['luck', 'hope', 'fingers crossed'] },
      { emoji: '🤙', name: 'call me hand', keywords: ['shaka', 'hang loose'] },
      { emoji: '👋', name: 'waving hand', keywords: ['hello', 'hi', 'bye', 'wave'] },
      { emoji: '🖐️', name: 'fingers splayed', keywords: ['stop', 'five', 'hand'] },
      { emoji: '✋', name: 'raised hand', keywords: ['stop', 'high five', 'halt'] },
      { emoji: '💪', name: 'flexed biceps', keywords: ['strong', 'muscle', 'power'] },
      { emoji: '👊', name: 'oncoming fist', keywords: ['fist bump', 'punch', 'brofist'] },
      { emoji: '✊', name: 'raised fist', keywords: ['solidarity', 'power', 'resist'] },
      { emoji: '🤟', name: 'love-you gesture', keywords: ['ily', 'rock', 'sign'] },
      { emoji: '🫰', name: 'finger heart', keywords: ['money', 'snap', 'love'] },
      { emoji: '☝️', name: 'index pointing up', keywords: ['one', 'attention', 'point'] },
      { emoji: '👉', name: 'pointing right', keywords: ['point', 'this', 'right'] },
      { emoji: '👈', name: 'pointing left', keywords: ['point', 'left'] },
      { emoji: '👇', name: 'pointing down', keywords: ['point', 'down', 'below'] },
      { emoji: '🖖', name: 'vulcan salute', keywords: ['spock', 'star trek', 'live long'] },
      { emoji: '✍️', name: 'writing hand', keywords: ['write', 'note', 'sign'] },
    ],
  },
  {
    name: 'People',
    emojis: [
      { emoji: '👀', name: 'eyes', keywords: ['look', 'watch', 'see', 'review'] },
      { emoji: '🧠', name: 'brain', keywords: ['smart', 'think', 'idea'] },
      { emoji: '🫂', name: 'people hugging', keywords: ['hug', 'support', 'together'] },
      { emoji: '👶', name: 'baby', keywords: ['infant', 'newborn', 'new'] },
      { emoji: '🧑‍💻', name: 'technologist', keywords: ['developer', 'coder', 'programmer'] },
      { emoji: '👩‍💻', name: 'woman technologist', keywords: ['developer', 'coder', 'engineer'] },
      { emoji: '👨‍💻', name: 'man technologist', keywords: ['developer', 'coder', 'engineer'] },
      { emoji: '🕵️', name: 'detective', keywords: ['investigate', 'spy', 'search'] },
      { emoji: '🦸', name: 'superhero', keywords: ['hero', 'save', 'rescue'] },
      { emoji: '🧙', name: 'mage', keywords: ['wizard', 'magic', 'spell'] },
      { emoji: '💁', name: 'tipping hand', keywords: ['info', 'sassy', 'help'] },
      { emoji: '🤷', name: 'shrugging', keywords: ['shrug', 'idk', 'dunno'] },
      { emoji: '🤦', name: 'facepalming', keywords: ['facepalm', 'disbelief', 'oops'] },
      { emoji: '🙋', name: 'raising hand', keywords: ['question', 'volunteer', 'me'] },
      { emoji: '🙇', name: 'bowing', keywords: ['sorry', 'apology', 'respect'] },
      { emoji: '🕺', name: 'man dancing', keywords: ['dance', 'party', 'disco'] },
      { emoji: '💃', name: 'woman dancing', keywords: ['dance', 'party', 'salsa'] },
      { emoji: '🏃', name: 'running', keywords: ['run', 'hurry', 'sprint'] },
      { emoji: '🧗', name: 'climbing', keywords: ['climb', 'challenge', 'effort'] },
    ],
  },
  {
    name: 'Nature',
    emojis: [
      { emoji: '🔥', name: 'fire', keywords: ['lit', 'hot', 'flame', 'burn'] },
      { emoji: '✨', name: 'sparkles', keywords: ['shiny', 'magic', 'clean', 'new'] },
      { emoji: '⭐', name: 'star', keywords: ['favorite', 'rating', 'starred'] },
      { emoji: '🌟', name: 'glowing star', keywords: ['shine', 'sparkle', 'special'] },
      { emoji: '💫', name: 'dizzy', keywords: ['stars', 'sparkle', 'spin'] },
      { emoji: '⚡', name: 'high voltage', keywords: ['lightning', 'fast', 'power'] },
      { emoji: '🌈', name: 'rainbow', keywords: ['pride', 'color', 'weather'] },
      { emoji: '☀️', name: 'sun', keywords: ['sunny', 'weather', 'bright'] },
      { emoji: '🌙', name: 'crescent moon', keywords: ['night', 'moon', 'late'] },
      { emoji: '☁️', name: 'cloud', keywords: ['weather', 'cloudy', 'sky'] },
      { emoji: '🌧️', name: 'rain cloud', keywords: ['rain', 'weather', 'wet'] },
      { emoji: '❄️', name: 'snowflake', keywords: ['cold', 'snow', 'winter', 'freeze'] },
      { emoji: '🌊', name: 'water wave', keywords: ['ocean', 'sea', 'surf'] },
      { emoji: '🌱', name: 'seedling', keywords: ['growth', 'plant', 'new'] },
      { emoji: '🌳', name: 'tree', keywords: ['nature', 'forest', 'branch'] },
      { emoji: '🌵', name: 'cactus', keywords: ['desert', 'plant', 'dry'] },
      { emoji: '🌸', name: 'cherry blossom', keywords: ['flower', 'spring', 'sakura'] },
      { emoji: '🌹', name: 'rose', keywords: ['flower', 'love', 'red'] },
      { emoji: '🍀', name: 'four leaf clover', keywords: ['luck', 'lucky', 'irish'] },
      { emoji: '🍁', name: 'maple leaf', keywords: ['autumn', 'fall', 'canada'] },
      { emoji: '🐝', name: 'honeybee', keywords: ['bee', 'buzz', 'busy'] },
      { emoji: '🐛', name: 'bug', keywords: ['insect', 'defect', 'issue', 'caterpillar'] },
      { emoji: '🦋', name: 'butterfly', keywords: ['insect', 'transform', 'pretty'] },
      { emoji: '🐶', name: 'dog', keywords: ['puppy', 'pet', 'woof'] },
      { emoji: '🐱', name: 'cat', keywords: ['kitten', 'pet', 'meow'] },
      { emoji: '🦊', name: 'fox', keywords: ['animal', 'clever', 'sly'] },
      { emoji: '🐼', name: 'panda', keywords: ['animal', 'bear', 'bamboo'] },
      { emoji: '🐢', name: 'turtle', keywords: ['slow', 'tortoise', 'shell'] },
      { emoji: '🦄', name: 'unicorn', keywords: ['magic', 'rare', 'mythical'] },
      { emoji: '🐙', name: 'octopus', keywords: ['sea', 'animal', 'tentacles'] },
      { emoji: '🦕', name: 'sauropod', keywords: ['dinosaur', 'legacy', 'old'] },
    ],
  },
  {
    name: 'Food',
    emojis: [
      { emoji: '☕', name: 'hot beverage', keywords: ['coffee', 'tea', 'morning'] },
      { emoji: '🍵', name: 'teacup', keywords: ['tea', 'green tea', 'matcha'] },
      { emoji: '🍺', name: 'beer', keywords: ['drink', 'pint', 'pub'] },
      { emoji: '🍻', name: 'clinking beers', keywords: ['cheers', 'celebrate', 'friends'] },
      { emoji: '🥂', name: 'clinking glasses', keywords: ['cheers', 'toast', 'celebrate'] },
      { emoji: '🍷', name: 'wine', keywords: ['drink', 'glass', 'red'] },
      { emoji: '🍕', name: 'pizza', keywords: ['food', 'slice', 'italian'] },
      { emoji: '🍔', name: 'hamburger', keywords: ['burger', 'food', 'fast food'] },
      { emoji: '🌮', name: 'taco', keywords: ['food', 'mexican', 'tuesday'] },
      { emoji: '🍣', name: 'sushi', keywords: ['food', 'japanese', 'fish'] },
      { emoji: '🍜', name: 'steaming bowl', keywords: ['noodles', 'ramen', 'soup'] },
      { emoji: '🍎', name: 'apple', keywords: ['fruit', 'red', 'healthy'] },
      { emoji: '🍌', name: 'banana', keywords: ['fruit', 'yellow'] },
      { emoji: '🍓', name: 'strawberry', keywords: ['fruit', 'berry', 'red'] },
      { emoji: '🍉', name: 'watermelon', keywords: ['fruit', 'summer', 'melon'] },
      { emoji: '🥑', name: 'avocado', keywords: ['fruit', 'toast', 'green'] },
      { emoji: '🥐', name: 'croissant', keywords: ['bread', 'pastry', 'french'] },
      { emoji: '🍩', name: 'doughnut', keywords: ['donut', 'sweet', 'sprinkles'] },
      { emoji: '🍪', name: 'cookie', keywords: ['sweet', 'biscuit', 'snack'] },
      { emoji: '🎂', name: 'birthday cake', keywords: ['cake', 'birthday', 'celebrate'] },
      { emoji: '🍫', name: 'chocolate', keywords: ['sweet', 'candy', 'bar'] },
      { emoji: '🍿', name: 'popcorn', keywords: ['movie', 'snack', 'drama'] },
      { emoji: '🧊', name: 'ice', keywords: ['cold', 'cube', 'frozen'] },
    ],
  },
  {
    name: 'Activity',
    emojis: [
      { emoji: '🎉', name: 'party popper', keywords: ['celebrate', 'congrats', 'yay', 'launch'] },
      { emoji: '🎊', name: 'confetti ball', keywords: ['celebrate', 'party', 'congrats'] },
      { emoji: '🎈', name: 'balloon', keywords: ['party', 'birthday', 'float'] },
      { emoji: '🎁', name: 'wrapped gift', keywords: ['present', 'birthday', 'surprise'] },
      { emoji: '🏆', name: 'trophy', keywords: ['win', 'award', 'champion'] },
      { emoji: '🥇', name: 'gold medal', keywords: ['first', 'win', 'best'] },
      { emoji: '🎯', name: 'bullseye', keywords: ['target', 'goal', 'exactly'] },
      { emoji: '🎮', name: 'video game', keywords: ['gaming', 'controller', 'play'] },
      { emoji: '🎧', name: 'headphone', keywords: ['music', 'listen', 'audio'] },
      { emoji: '🎤', name: 'microphone', keywords: ['sing', 'voice', 'record'] },
      { emoji: '🎨', name: 'artist palette', keywords: ['art', 'design', 'paint'] },
      { emoji: '🎬', name: 'clapper board', keywords: ['film', 'movie', 'action'] },
      { emoji: '⚽', name: 'soccer ball', keywords: ['football', 'sport', 'goal'] },
      { emoji: '🏀', name: 'basketball', keywords: ['sport', 'hoops', 'nba'] },
      { emoji: '🚀', name: 'rocket', keywords: ['launch', 'ship', 'fast', 'deploy'] },
      { emoji: '🛸', name: 'flying saucer', keywords: ['ufo', 'alien', 'abduct'] },
      { emoji: '🏁', name: 'chequered flag', keywords: ['finish', 'race', 'done'] },
    ],
  },
  {
    name: 'Objects',
    emojis: [
      { emoji: '💡', name: 'light bulb', keywords: ['idea', 'insight', 'tip'] },
      { emoji: '🔧', name: 'wrench', keywords: ['fix', 'tool', 'repair'] },
      { emoji: '🔨', name: 'hammer', keywords: ['build', 'tool', 'nail'] },
      { emoji: '🛠️', name: 'hammer and wrench', keywords: ['tools', 'build', 'maintenance'] },
      { emoji: '⚙️', name: 'gear', keywords: ['settings', 'config', 'engine'] },
      { emoji: '🧰', name: 'toolbox', keywords: ['tools', 'kit', 'repair'] },
      { emoji: '🔒', name: 'locked', keywords: ['lock', 'secure', 'private'] },
      { emoji: '🔓', name: 'unlocked', keywords: ['unlock', 'open', 'public'] },
      { emoji: '🔑', name: 'key', keywords: ['access', 'password', 'secret'] },
      { emoji: '📌', name: 'pushpin', keywords: ['pin', 'important', 'note'] },
      { emoji: '📎', name: 'paperclip', keywords: ['attach', 'file', 'clip'] },
      { emoji: '📋', name: 'clipboard', keywords: ['copy', 'list', 'paste'] },
      { emoji: '📝', name: 'memo', keywords: ['note', 'write', 'edit'] },
      { emoji: '📄', name: 'page', keywords: ['document', 'file', 'paper'] },
      { emoji: '📊', name: 'bar chart', keywords: ['stats', 'data', 'metrics'] },
      { emoji: '📈', name: 'chart increasing', keywords: ['growth', 'up', 'trend'] },
      { emoji: '📉', name: 'chart decreasing', keywords: ['drop', 'down', 'decline'] },
      { emoji: '🗑️', name: 'wastebasket', keywords: ['delete', 'trash', 'remove'] },
      { emoji: '📦', name: 'package', keywords: ['box', 'release', 'ship', 'bundle'] },
      { emoji: '💾', name: 'floppy disk', keywords: ['save', 'disk', 'storage'] },
      { emoji: '💻', name: 'laptop', keywords: ['computer', 'code', 'work'] },
      { emoji: '🖥️', name: 'desktop computer', keywords: ['monitor', 'screen', 'display'] },
      { emoji: '📱', name: 'mobile phone', keywords: ['phone', 'mobile', 'device'] },
      { emoji: '🔍', name: 'magnifying glass', keywords: ['search', 'find', 'zoom'] },
      { emoji: '🔔', name: 'bell', keywords: ['notification', 'alert', 'remind'] },
      { emoji: '⏰', name: 'alarm clock', keywords: ['time', 'alarm', 'deadline'] },
      { emoji: '⏳', name: 'hourglass', keywords: ['wait', 'time', 'pending'] },
      { emoji: '🧪', name: 'test tube', keywords: ['experiment', 'test', 'lab'] },
      { emoji: '🔬', name: 'microscope', keywords: ['research', 'inspect', 'science'] },
      { emoji: '🩹', name: 'adhesive bandage', keywords: ['patch', 'fix', 'bandaid'] },
      { emoji: '🧹', name: 'broom', keywords: ['clean', 'sweep', 'cleanup'] },
      { emoji: '🗺️', name: 'world map', keywords: ['map', 'plan', 'roadmap'] },
      { emoji: '📚', name: 'books', keywords: ['read', 'docs', 'learn'] },
      { emoji: '✏️', name: 'pencil', keywords: ['write', 'edit', 'draft'] },
      { emoji: '🖊️', name: 'pen', keywords: ['write', 'sign', 'ink'] },
      { emoji: '🔗', name: 'link', keywords: ['url', 'chain', 'connect'] },
      { emoji: '👑', name: 'crown', keywords: ['king', 'queen', 'best'] },
    ],
  },
  {
    name: 'Symbols',
    emojis: [
      { emoji: '❤️', name: 'red heart', keywords: ['love', 'like', 'heart'] },
      { emoji: '🧡', name: 'orange heart', keywords: ['love', 'heart', 'orange'] },
      { emoji: '💛', name: 'yellow heart', keywords: ['love', 'heart', 'yellow'] },
      { emoji: '💚', name: 'green heart', keywords: ['love', 'heart', 'green'] },
      { emoji: '💙', name: 'blue heart', keywords: ['love', 'heart', 'blue'] },
      { emoji: '💜', name: 'purple heart', keywords: ['love', 'heart', 'purple'] },
      { emoji: '🖤', name: 'black heart', keywords: ['love', 'heart', 'dark'] },
      { emoji: '🤍', name: 'white heart', keywords: ['love', 'heart', 'pure'] },
      { emoji: '💔', name: 'broken heart', keywords: ['breakup', 'sad', 'heartbreak'] },
      { emoji: '💖', name: 'sparkling heart', keywords: ['love', 'sparkle', 'heart'] },
      { emoji: '✅', name: 'check mark', keywords: ['done', 'yes', 'approved', 'complete'] },
      { emoji: '☑️', name: 'ballot box with check', keywords: ['checked', 'todo', 'tick'] },
      { emoji: '❌', name: 'cross mark', keywords: ['no', 'wrong', 'fail', 'error'] },
      { emoji: '⛔', name: 'no entry', keywords: ['stop', 'blocked', 'forbidden'] },
      { emoji: '⚠️', name: 'warning', keywords: ['caution', 'alert', 'careful'] },
      { emoji: '❓', name: 'question mark', keywords: ['question', 'help', 'why'] },
      { emoji: '❗', name: 'exclamation mark', keywords: ['important', 'alert', 'bang'] },
      { emoji: '💯', name: 'hundred points', keywords: ['100', 'perfect', 'agree'] },
      { emoji: '➕', name: 'plus', keywords: ['add', 'more', 'increase'] },
      { emoji: '➖', name: 'minus', keywords: ['remove', 'less', 'decrease'] },
      { emoji: '♻️', name: 'recycling symbol', keywords: ['reuse', 'recycle', 'refactor'] },
      { emoji: '🆕', name: 'new button', keywords: ['new', 'fresh', 'latest'] },
      { emoji: '🆗', name: 'ok button', keywords: ['ok', 'fine', 'agreed'] },
      { emoji: '🔴', name: 'red circle', keywords: ['record', 'critical', 'blocker'] },
      { emoji: '🟢', name: 'green circle', keywords: ['ok', 'go', 'pass'] },
      { emoji: '🟡', name: 'yellow circle', keywords: ['warning', 'pending', 'hold'] },
      { emoji: '🔵', name: 'blue circle', keywords: ['info', 'neutral'] },
      { emoji: '♾️', name: 'infinity', keywords: ['endless', 'forever', 'loop'] },
      { emoji: '💬', name: 'speech balloon', keywords: ['comment', 'chat', 'talk'] },
      { emoji: '💭', name: 'thought balloon', keywords: ['think', 'idea', 'dream'] },
    ],
  },
]

/** Every emoji, flattened in category order — the picker's grid and its search share one list. */
export const EMOJI: Emoji[] = EMOJI_CATEGORIES.flatMap((c) => c.emojis)

/** Case-insensitive substring match over name AND keywords. A blank query is the whole list.
 *  Name matches sort ahead of keyword-only matches: the picker's Enter key takes the FIRST result,
 *  so searching `star` has to reach ⭐ before 💫, which only mentions stars in passing. */
export function searchEmoji(query: string): Emoji[] {
  const q = query.trim().toLowerCase()
  if (!q) return EMOJI
  const named: Emoji[] = []
  const tagged: Emoji[] = []
  for (const e of EMOJI) {
    if (e.name.includes(q)) named.push(e)
    else if (e.keywords.some((k) => k.includes(q))) tagged.push(e)
  }
  return [...named, ...tagged]
}
