// Build the glance.db browser client into a string module both workers serve (main worker at
// /api/glance.js, content worker at /_glance/db.js). Same model as build-annotate: bundle
// client.ts → IIFE, stamp a content version. Output: src/glancedb/bundle.ts (committed).
//
// Run from packages/api:  bun run build:db
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

const here = import.meta.dir
const srcDir = join(here, '..', 'src', 'glancedb')

const built = await Bun.build({
  entrypoints: [join(srcDir, 'client.ts')],
  minify: true,
  format: 'iife',
  target: 'browser',
})
if (!built.success) {
  for (const log of built.logs) console.error(log)
  throw new Error('glance.db client build failed')
}

const js = await built.outputs[0].text()
const version = new Bun.CryptoHasher('sha256').update(js).digest('hex').slice(0, 8)

const out = `// GENERATED by scripts/build-db.ts — do not edit by hand.
// Run \`bun run build:db\` after changing glancedb/client.ts.
// biome-ignore-all lint/suspicious/noTemplateCurlyInString: minified bundle carries template literals inside the string
export const GLANCE_DB_JS = ${JSON.stringify(js)}
export const GLANCE_DB_VERSION = ${JSON.stringify(version)}
`
writeFileSync(join(srcDir, 'bundle.ts'), out)
console.log(`glance.db client: ${js.length}B js → v${version}`)
