// Generate src/install-script.ts from the repo-root install.sh so the main worker can serve the
// installer at /api/install (single source of truth: edit install.sh, then `bun run build:install`).
// Mirrors build-annotate.ts — the worker has no asset pipeline for arbitrary files.
//
// Run from packages/api:  bun run build:install
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const here = import.meta.dir
const sh = readFileSync(join(here, '..', '..', '..', 'install.sh'), 'utf8')

const out = `// GENERATED by scripts/build-install.ts from the repo-root install.sh — do not edit by hand.
// Run \`bun run build:install\` after changing install.sh.
export const INSTALL_SH = ${JSON.stringify(sh)}
`
writeFileSync(join(here, '..', 'src', 'install-script.ts'), out)
console.log(`install script: ${sh.length}B → src/install-script.ts`)
