// Build the design themes into committed string modules (same groove as build-annotate.ts —
// neither worker has a static-asset pipeline). Scans themes/<slug>/ for theme.css + theme.json
// + DESIGN.md and emits THREE modules so each worker bundles only what it serves:
//   src/themes/registry.ts — slugs + display meta + isTheme(). Tiny; safe for ANY bundle
//                            (schema.ts stays catalog-free; routes validate against this).
//   src/themes/css.ts      — the stylesheets. Imported ONLY by the content worker.
//   src/themes/briefs.ts   — the DESIGN.md agent briefs. Imported ONLY by the main worker.
//
// Run from packages/api:  bun run build:themes
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const here = import.meta.dir
const themesDir = join(here, '..', 'themes')
const outDir = join(here, '..', 'src', 'themes')

const slugs = readdirSync(themesDir, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name)
  .sort()
if (slugs.length === 0) throw new Error('no theme directories under themes/')
// Catalog order = picker order. theme.json may set `order` (lower first); unnumbered themes
// follow alphabetically. The brand theme pins itself to the top with order: 0.
const orderOf = (slug: string): number => {
  try {
    const { order } = JSON.parse(readFileSync(join(themesDir, slug, 'theme.json'), 'utf8')) as { order?: number }
    return typeof order === 'number' ? order : 999
  } catch {
    return 999
  }
}
slugs.sort((a, b) => orderOf(a) - orderOf(b) || a.localeCompare(b))

const info: { slug: string; name: string; description: string }[] = []
const css: Record<string, string> = {}
const briefs: Record<string, string> = {}
const fonts: Record<string, string> = {} // filename -> base64 woff2 (self-hosted, issue #155)
for (const slug of slugs) {
  if (!/^[a-z0-9-]+$/.test(slug)) throw new Error(`theme slug must be [a-z0-9-]+: ${slug}`)
  const dir = join(themesDir, slug)
  const meta = JSON.parse(readFileSync(join(dir, 'theme.json'), 'utf8')) as { name?: string; description?: string }
  if (!meta.name || !meta.description) throw new Error(`themes/${slug}/theme.json needs name + description`)
  info.push({ slug, name: meta.name, description: meta.description })
  css[slug] = readFileSync(join(dir, 'theme.css'), 'utf8')
  briefs[slug] = readFileSync(join(dir, 'DESIGN.md'), 'utf8')
  // Optional vendored fonts (themes/<slug>/fonts/*.woff2): served first-party at
  // /_glance/theme/fonts/<file> so a themed page never calls out to Google (issue #155).
  const fontsDir = join(dir, 'fonts')
  if (existsSync(fontsDir)) {
    for (const f of readdirSync(fontsDir).filter((name) => name.endsWith('.woff2')).sort()) {
      if (fonts[f]) throw new Error(`duplicate font filename across themes: ${f}`)
      fonts[f] = readFileSync(join(fontsDir, f)).toString('base64')
    }
  }
}

// One version across all themes (the annotate-bundle idiom): any CSS OR font change re-busts
// every theme link, which is cheap — themes are a handful of small files.
const version = new Bun.CryptoHasher('sha256')
  .update(slugs.map((s) => css[s]).join('\0') + Object.values(fonts).join('\0'))
  .digest('hex')
  .slice(0, 8)
// Authored CSS references fonts as url('/_glance/theme/fonts/x.woff2?v=__THEMES_VERSION__') —
// substitute the real version so a font swap busts the immutable cache.
for (const slug of slugs) css[slug] = css[slug].replaceAll('__THEMES_VERSION__', version)

const banner = `// GENERATED by scripts/build-themes.ts — do not edit by hand.
// Run \`bun run build:themes\` after changing anything under themes/.
`
writeFileSync(
  join(outDir, 'registry.ts'),
  `${banner}export const THEME_INFO = ${JSON.stringify(info, null, 2)} as const

export type ThemeSlug = (typeof THEME_INFO)[number]['slug']

const SLUGS = new Set<string>(THEME_INFO.map((t) => t.slug))

/** True when \`v\` names a shipped theme. The single validation authority for sites.theme. */
export function isTheme(v: unknown): v is ThemeSlug {
  return typeof v === 'string' && SLUGS.has(v)
}

/** Map a raw wire value (form field / JSON) to a stored theme value: ''/'none'/'default' — and
 *  any non-string — clear to null (default = the page's own design). Pair with isTheme at the
 *  route boundary so an unknown slug 400s instead of silently serving unthemed (the
 *  normalizeVisibility + isVisibility idiom). */
export function normalizeTheme(raw: unknown): string | null {
  return typeof raw === 'string' && raw !== '' && raw !== 'none' && raw !== 'default' ? raw : null
}

/** Cache-busting version for /_glance/theme/*.css?v= links. Duplicated from css.ts so the MAIN
 *  worker (and the web client via /api/themes) can build hrefs without importing the CSS strings. */
export const THEMES_VERSION = ${JSON.stringify(version)}
`,
)
writeFileSync(
  join(outDir, 'css.ts'),
  `${banner}export const THEME_CSS: Record<string, string> = ${JSON.stringify(css, null, 2)}

export const THEMES_VERSION = ${JSON.stringify(version)}
`,
)
writeFileSync(
  join(outDir, 'fonts.ts'),
  `${banner}export const THEME_FONTS: Record<string, string> = ${JSON.stringify(fonts, null, 2)}
`,
)
writeFileSync(
  join(outDir, 'briefs.ts'),
  `${banner}export const THEME_BRIEFS: Record<string, string> = ${JSON.stringify(briefs, null, 2)}
`,
)
console.log(`themes bundle: ${slugs.join(', ')} → v${version}`)
