// Generate src/whats-new/catalog.ts from the authored notes in src/whats-new/notes/*.md so the
// main worker serves the "What's New" release notes with the body markdown pre-rendered at build
// time (single source of truth: add a .md, then `bun run build:whatsnew`). Mirrors build-install.ts
// — the worker has no asset pipeline, and buildCatalog's guards fail the build loudly on a bad note.
//
// Run from packages/api:  bun run build:whatsnew
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { buildCatalog } from '../src/whats-new/bake'

const here = import.meta.dir
const notesDir = join(here, '..', 'src', 'whats-new', 'notes')

const files = readdirSync(notesDir)
  .filter((f) => f.endsWith('.md'))
  .sort()
const raws = files.map((f) => readFileSync(join(notesDir, f), 'utf8'))

const { releases, newestDate } = await buildCatalog(raws)

const out = `// GENERATED by scripts/build-whatsnew.ts from src/whats-new/notes/*.md — do not edit by hand.
// Run \`bun run build:whatsnew\` after adding or editing a release note.
import type { Release } from './bake'

export const RELEASES: Release[] = ${JSON.stringify(releases, null, 2)}

export const NEWEST_RELEASE_DATE: string | null = ${JSON.stringify(newestDate)}
`
writeFileSync(join(here, '..', 'src', 'whats-new', 'catalog.ts'), out)
console.log(`whats-new: ${files.length} note(s) → ${releases.length} release(s), newest ${newestDate} → src/whats-new/catalog.ts`)
