// GENERATED by scripts/build-whatsnew.ts from src/whats-new/notes/*.md — do not edit by hand.
// Run `bun run build:whatsnew` after adding or editing a release note.
import type { Release } from './bake'

export const RELEASES: Release[] = [
  {
    "slug": "comments-tab",
    "title": "All your comments, one feed",
    "date": "2026-07-11T12:00:00.000Z",
    "featured": true,
    "bodyHtml": "<p>The dashboard has a new <strong>Comments</strong> tab: every <strong>mention of you</strong> and every <strong>comment you wrote</strong>, across all your sites, in one newest-first feed.</p>\n<ul>\n<li>Click any row to jump straight to that thread on the page, with the review rail already open</li>\n<li>Rows show where the conversation lives and whether it&#39;s still open or already resolved</li>\n<li>Mentions stay actionable here even after you&#39;ve read them in the bell</li>\n</ul>\n"
  },
  {
    "slug": "voice-comments",
    "title": "Comment with your voice",
    "date": "2026-07-01T15:00:00.000Z",
    "featured": true,
    "bodyHtml": "<p>Some feedback is faster said than typed. You can now <strong>record a voice comment</strong> right on a site — pin it to the exact spot you&#39;re talking about, and your teammates can play it back inline.</p>\n<ul>\n<li>Record straight from the comment composer</li>\n<li>Voice notes are transcribed automatically, so the thread stays searchable</li>\n<li>Play, pause, and scrub without leaving the page</li>\n</ul>\n"
  },
  {
    "slug": "external-links-new-tab",
    "title": "Links open where you expect",
    "date": "2026-06-20T09:00:00.000Z",
    "featured": false,
    "bodyHtml": "<p>Links in a shared site that point somewhere <strong>off Glance</strong> now open in a <strong>new tab</strong>, so a click never yanks a reviewer out of the page they were reading.</p>\n<p>Internal links and in-page anchors keep navigating in place, exactly as before — only genuinely external destinations get the new tab.</p>\n"
  }
]

export const NEWEST_RELEASE_DATE: string | null = "2026-07-11T12:00:00.000Z"
