// GENERATED by scripts/build-whatsnew.ts from src/whats-new/notes/*.md — do not edit by hand.
// Run `bun run build:whatsnew` after adding or editing a release note.
import type { Release } from './bake'

export const RELEASES: Release[] = [
  {
    "slug": "realtime-comments",
    "title": "Comments arrive live",
    "date": "2026-08-01T10:00:00.000Z",
    "featured": true,
    "bodyHtml": "<p>A comment someone else leaves now shows up while you&#39;re reading. No refresh, no polling, no &quot;let me reload and check&quot;.</p>\n<ul>\n<li><strong>New comments and replies appear as they&#39;re posted</strong> — in the panel and on the page</li>\n<li><strong>You only ever receive what you could already open.</strong> The live feed is gated exactly like the page is; it is not a second way in</li>\n<li><strong>Leave a tab open and it stays honest.</strong> If the connection drops it reconnects and re-reads the thread, so an old tab catches up instead of quietly going stale</li>\n<li><strong>See a reply coming.</strong> While someone is typing a reply, the thread says so</li>\n<li><strong>Nothing to turn on</strong> — open a page with comments and it&#39;s already listening</li>\n</ul>\n<p>The connection renews itself every few minutes. A comment that lands exactly on a renewal arrives a beat later rather than instantly — everything else is immediate.</p>\n"
  },
  {
    "slug": "star-a-page",
    "title": "Star a page",
    "image": "star-a-page.png",
    "date": "2026-07-29T18:00:00.000Z",
    "featured": true,
    "bodyHtml": "<p>The page you keep hunting for in search is now one click away. Hit the <strong>star</strong> on any page — from a row on your dashboard or from the top bar while you&#39;re reading it — and it pins to a new <strong>Starred</strong> tab.</p>\n<ul>\n<li><strong>Star from wherever you are</strong> — the row on the dashboard, or the top bar of the page you&#39;re already reading</li>\n<li><strong>Starred is always there</strong>, second tab along, so you can find it before you&#39;ve starred anything</li>\n<li><strong>Newest star first</strong> — the tab is ordered by when <em>you</em> pinned each page, not when it was created</li>\n<li><strong>Your stars are yours.</strong> Nobody can see what you&#39;ve starred, and starring never changes who can open a page</li>\n<li><strong>If you can open it, you can star it</strong> — including your own private pages and private pages someone shared with you</li>\n</ul>\n<p>Star a page you later lose access to and it quietly drops out of the tab — if you get access again, it comes right back.</p>\n"
  },
  {
    "slug": "live-data",
    "title": "Live data on any page",
    "image": "live-data.png",
    "date": "2026-07-29T09:00:00.000Z",
    "featured": true,
    "bodyHtml": "<p>A page you deploy can now <strong>store data and update itself</strong> — no backend to run, nothing to host. Ask for a form, a poll, a board or a dashboard, and it gets a real data store: <code>glance.db</code>.</p>\n<ul>\n<li><strong>Anyone who can open the site can add to it</strong>, attributed to them — so forms and surveys just work</li>\n<li><strong>Changes are pushed, not polled.</strong> Every open page updates the moment something lands, with no refresh button</li>\n<li><strong>Your scripts can write too</strong> — a cron job or CI step posts to the site and every dashboard watching it reacts</li>\n<li>By default you only see what <strong>you</strong> added; a <code>shared-…</code> collection is one everybody watching sees together</li>\n<li>The site <strong>owner</strong> can edit or remove any entry, so a public board stays moderatable</li>\n</ul>\n<p>Leave a page open overnight and it catches up on whatever it missed — no stale tab, no reload.</p>\n"
  },
  {
    "slug": "tldr-summaries",
    "title": "TL;DR any site",
    "image": "tldr-summaries.png",
    "date": "2026-07-14T18:00:00.000Z",
    "featured": true,
    "bodyHtml": "<p>Every site now has an AI summary one click away: hit <strong>TL;DR</strong> in the viewer top bar, or <strong>Summary</strong> from a site&#39;s row menu on the dashboard.</p>\n<ul>\n<li>Summaries are cached — reopening one is instant and free until the site&#39;s content changes</li>\n<li>When content changes, the sheet shows what version the summary was written for and offers a one-click update</li>\n<li>Sites with a summary show a sparkle next to their name on the dashboard</li>\n</ul>\n"
  },
  {
    "slug": "fork-a-site",
    "title": "Make it your own — fork any site",
    "image": "fork-a-site.png",
    "date": "2026-07-14T12:00:00.000Z",
    "featured": false,
    "bodyHtml": "<p>Found a site you want to build on? <strong>Fork</strong> it. You get your own copy in your own space — edit it, redeploy it, break it, without touching the original.</p>\n<ul>\n<li>Fork from the <strong>⋯ menu</strong> on the dashboard, or straight from the <strong>top bar</strong> of any site you&#39;re viewing</li>\n<li>Anyone who can open a site can fork it, so a page someone shared with you is yours to riff on</li>\n<li>The copy is completely independent: your own files, your own comments, your own sharing</li>\n<li>Handy before a risky redeploy — fork first, and you&#39;ve got a snapshot to fall back on</li>\n</ul>\n"
  },
  {
    "slug": "comments-tab",
    "title": "All your comments, one feed",
    "image": "comments-tab.png",
    "date": "2026-07-11T12:00:00.000Z",
    "featured": false,
    "bodyHtml": "<p>The dashboard has a new <strong>Comments</strong> tab: every <strong>mention of you</strong> and every <strong>comment you wrote</strong>, across all your sites, in one newest-first feed.</p>\n<ul>\n<li>Click any row to jump straight to that thread on the page, with the review rail already open</li>\n<li>Rows show where the conversation lives and whether it&#39;s still open or already resolved</li>\n<li>Mentions stay actionable here even after you&#39;ve read them in the bell</li>\n</ul>\n"
  },
  {
    "slug": "voice-comments",
    "title": "Comment with your voice",
    "image": "voice-comments.png",
    "date": "2026-07-01T15:00:00.000Z",
    "featured": false,
    "bodyHtml": "<p>Some feedback is faster said than typed. You can now <strong>record a voice comment</strong> right on a site — pin it to the exact spot you&#39;re talking about, and your teammates can play it back inline.</p>\n<ul>\n<li>Record straight from the comment composer</li>\n<li>Voice notes are transcribed automatically, so the thread stays searchable</li>\n<li>Play, pause, and scrub without leaving the page</li>\n</ul>\n"
  },
  {
    "slug": "external-links-new-tab",
    "title": "Links open where you expect",
    "image": "external-links-new-tab.png",
    "date": "2026-06-20T09:00:00.000Z",
    "featured": false,
    "bodyHtml": "<p>Links in a shared site that point somewhere <strong>off Glance</strong> now open in a <strong>new tab</strong>, so a click never yanks a reviewer out of the page they were reading.</p>\n<p>Internal links and in-page anchors keep navigating in place, exactly as before — only genuinely external destinations get the new tab.</p>\n"
  }
]

export const NEWEST_RELEASE_DATE: string | null = "2026-08-01T10:00:00.000Z"
