// Generate skill-content.ts from glance-cli/SKILL.md so `glance skill install` can ship the skill
// INSIDE the standalone binary — no Node/npx needed at install time (the binary audience usually
// has neither). Single source of truth: edit glance-cli/SKILL.md, then `bun run build:skill`.
//
// Run from packages/cli:  bun run build:skill
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const here = import.meta.dir
const md = readFileSync(join(here, '..', '..', '..', 'glance-cli', 'SKILL.md'), 'utf8')

const out = `// GENERATED by scripts/build-skill.ts from glance-cli/SKILL.md — do not edit by hand.
// Run \`bun run build:skill\` after changing the skill.
export const SKILL_NAME = 'glance-cli'
export const SKILL_MD = ${JSON.stringify(md)}
`
writeFileSync(join(here, '..', 'skill-content.ts'), out)
console.log(`skill: ${md.length}B → skill-content.ts`)
