// GENERATED by scripts/build-annotate.ts — do not edit by hand.
// Run `bun run build:annotate` after changing client.ts / client.css.
export const ANNOTATE_JS = "(()=>{(()=>{let f=window.__GLANCE__;if(!f)return;try{window.parent.postMessage({type:\"glance:ready\",filePath:f.filePath},f.appOrigin)}catch{}})();})();\n"
export const ANNOTATE_CSS = "/* Annotate-mode styles, served at /_glance/annotate.css and injected alongside the client.\n   Custom Highlight API paint for anchored comment ranges; span-wrap fallback uses .glance-hl. */\n::highlight(glance-comment) {\n  background-color: rgba(255, 213, 0, 0.4);\n}\n.glance-hl {\n  background-color: rgba(255, 213, 0, 0.4);\n  cursor: pointer;\n}\n"
export const ANNOTATE_VERSION = "ef4f0c41"
